version: '3'
services:
  localstack-estudo:
    image: localstack/localstack
    environment:
      - AWS_DEFAULT_REGION=eu-central-1
      - SERVICES=s3,sqs
      - DOCKER_HOST=unix:///var/run/docker.sock
      - EDGE_PORT=4566
    ports:
      - "4566:4566"
